# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: dbrest

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/flarco/dbio' go.mod
    - go mod tidy

builds:
  - main: .
    
    env:
      - CGO_ENABLED=1

    goarch:
      - amd64
      - arm64
    goos:
      # - linux
      # - windows
      - darwin
    ldflags:
      - "-X 'github.com/dbrest-io/dbrest/state.Version={{.Version}}'"

universal_binaries:
  - id: dbrest
    replace: false
  
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

snapshot:
  name_template: "{{ incpatch .Version }}"

release:
  mode: replace
  header: |
    ## dbREST {{ .Tag }} ({{ .Date }})

brews:
  - name: dbrest
    tap:
      owner: dbrest-io
      name: homebrew-dbrest
      branch: main

    homepage: https:/github.com/dbrest-io/dbrest

    description: "dbREST is an API backend that you can put in front of your database. Ever wanted to spin up an API service in front of your Snowflake, MySQL or even SQLite database? Well, dbREST allows that!"